---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node:10
  commands:
  - npm install
  - npm test

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
- name: test
  image: node:10
  commands:
  - npm install
  - npm test

- name: npm
  image: plugins/npm
  settings:
    username: redneckz
    password:
      from_secret: npm_password
    email: aalexandrovv@gmail.com
    access: public

trigger:
  event:
  - tag
